[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python backend/scripts/build_actor_index_insightface.py --dataset dataset/ --clusters 1"]

[start]
cmd = "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app"
