[build]
builder = "nixpacks"

[deploy]
startCommand = "PYTHONPATH=/app:$PYTHONPATH uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
